# Generated by Django 5.2 on 2025-04-26 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BPMNDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('xml_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtomicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('atomic_type', models.CharField(choices=[('collect', 'Collect'), ('dispatch', 'Dispatch'), ('process&monitor', 'Process & Monitor'), ('display', 'Display')], max_length=50)),
                ('input_params', models.JSONField(default=list)),
                ('output_params', models.JSONField(default=list)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('url', models.URLField()),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atomic_services', to='editor.bpmndiagram')),
            ],
        ),
    ]
