def build_prompt(workflow_spec: str) -> str:
    prompt = [
        f"Genera codice per più progetti Laravel distinti (uno per ciascun attore) a partire dalla seguente specifica BPMN e basandoti sulle istruzioni fornite riguardo l'utilizzo della libreria Laravel Workflow.",
        "",
        "Ogni attore rappresenta un'entità autonoma, con un proprio progetto Laravel separato.",
        "Il codice di ciascun attore non deve essere inserito nello stesso progetto degli altri attori.",
        "",
        "Specifiche complete del BPMN (in formato JSON):",
        "```json",
        workflow_spec.strip(),
        "```",
        "",
        "# REQUISITI DI GENERAZIONE:",
        "- Identifica tutti gli attori presenti nella specifica (campo 'actors').",
        "- Per ogni attore genera il codice che popolerà il proprio progetto Laravel dedicato.",
        "- Ogni attore avrà i propri workflow, controller, servizi, activity e route, indipendenti da quelli degli altri.",
        "- Le comunicazioni tra attori (servizi di tipo 'dispatch' o 'collect') avvengono tramite HTTP REST e devono essere rappresentate come chiamate verso endpoint pubblici degli altri attori.",
        "- Utilizza la libreria Laravel Workflow per implementare i workflow e le activity.",
        "- Se nella specifica del BPMN un attore è coinvolto in un CPPN, crea un workflow dedicato nella cartella app/Workflows che gestisce tutte le attività dell'attore all'interno del CPPN.",
        "- Per ogni CPPS appartenente ad un attore, crea un workflow dedicato nella cartella app/Workflows che gestisce le attività dell'attore all'interno del CPPS.",
        "- Se un attore compare in 2 o più CPPN, crea un workflow separato per ogni CPPN in cui è coinvolto.",
        "- Tratta un CPPS come un ChildWorkflowStub come descritto nelle istruzioni della libreria Laravel Workflow, da inserire all'interno del workflow principale (CPPN) dell'attore.",
        "- Basati sulle istruzioni e gli esempi riportati in questo prompt per la generazione del codice Laravel.",
        "",
        "# STRUTTURA DI OGNI PROGETTO LARAVEL (PER OGNI ATTORE):",
        "- app/Workflows/: contiene le classi di orchestrazione dei workflow (es. ProductionLeaderWorkflow.php).",
        "- app/Activities/: contiene le activity usate dal workflow.",
        "- app/Services/: contiene le classi di servizio che implementano la logica di business.",
        "- app/Http/Controllers/: contiene i controller che espongono endpoint REST per avviare workflow o servizi atomici.",
        "- routes/api.php: definisce le route HTTP necessarie.",
        "",
        "# OGNI ATTORE DOVRÀ AVERE:",
        "1. Una o più classi Workflow per orchestrare le Activity in base al processo BPMN.",
        "2. Una classe per ogni Activity.",
        "3. Una classe Service per ogni servizio atomico.",
        "4. Un Controller per esporre endpoint pubblici.",
        "5. Le route associate, per ogni servizio atomico e CPPS registrate in routes/api.php.",
        "6. In caso di CPPS, il workflow principale dell'attore deve includere i ChildWorkflowStub per ogni CPPS in cui è coinvolto.",
        "7. Nel file api.php l'istruzione 'Webhooks::routes();' deve essere presente per abilitare i webhooks.",
        "",
        "# REGOLE PER I SERVIZI ATOMICI:",
        "- I servizi di tipo 'dispatch' devono effettuare chiamate HTTP POST verso endpoint di altri attori.",
        "- I servizi di tipo 'collect' devono ricevere chiamate HTTP e gestire i dati ricevuti nel rispettivo controller.",
        "",
        "# REGOLE DI DENOMINAZIONE DEI FILE:",
        "- Workflow: <ActorName>Workflow.php",
        "- Activity: <ServiceName>Activity.php",
        "- Service: <ServiceName>Service.php",
        "- Controller: <ServiceName>Controller.php",
        "",
        "# ISTRUZIONI PER L'USO DELLA LIBRERIA LARAVEL WORKFLOW:",
        "",
        "## Child Workflows ##",
        "- I child workflows permettono di suddividere processi complessi in sotto-processi gestibili.",
        "- Un child workflow è identico a un normale workflow, ma viene richiamato con `ChildWorkflowStub::make()` all’interno del workflow padre.",
        "- Esempio:",
        "```php",
        "use Workflow\\ChildWorkflowStub;",
        "use Workflow\\Workflow;",
        "",
        "class ParentWorkflow extends Workflow {",
        "    public function execute() {",
        "        $childResult = yield ChildWorkflowStub::make(ChildWorkflow::class);",
        "    }",
        "}",
        "```",
        "",
        "## Signals ##",
        "- I signals permettono di inviare eventi a un workflow dall'esterno.",
        "- Si definiscono con l’attributo `#[SignalMethod]` su un metodo del workflow.",
        "- Esempio:",
        "```php",
        "use Workflow\\SignalMethod;",
        "use Workflow\\Workflow;",
        "",
        "class MyWorkflow extends Workflow {",
        "    protected $ready = false;",
        "",
        "    #[SignalMethod]",
        "    public function setReady($ready) {",
        "        $this->ready = $ready;",
        "    }",
        "}",
        "```",
        "- I signals vengono inviati con `WorkflowStub::load($workflowId)` e chiamando il metodo segnato come Signal:",
        "```php",
        "$workflow = WorkflowStub::load($workflowId);",
        "$workflow->setReady(true);",
        "```",
        "- Per sospendere l'esecuzione fino alla ricezione di un segnale, si può usare `WorkflowStub::await(fn () => $this->ready);` all’interno di un workflow.",
        "",
        "## Concurrency ##",
        "- Le activity possono essere eseguite in serie o in parallelo usando `ActivityStub::make()` e `ActivityStub::all()`.",
        "- Esecuzione in serie:",
        "```php",
        "return [",
        "    yield ActivityStub::make(MyActivity1::class),",
        "    yield ActivityStub::make(MyActivity2::class),",
        "    yield ActivityStub::make(MyActivity3::class),",
        "];",
        "```",
        "- Esecuzione in parallelo:",
        "```php",
        "return yield ActivityStub::all([",
        "    ActivityStub::make(MyActivity1::class),",
        "    ActivityStub::make(MyActivity2::class),",
        "    ActivityStub::make(MyActivity3::class),",
        "]);",
        "```",
        "- È possibile combinare seriale e parallelo:",
        "```php",
        "return [",
        "    yield ActivityStub::make(MyActivity1::class),",
        "    yield ActivityStub::all([",
        "        ActivityStub::async(fn () => [",
        "            yield ActivityStub::make(MyActivity2::class),",
        "            yield ActivityStub::make(MyActivity3::class),",
        "        ]),",
        "        ActivityStub::make(MyActivity4::class),",
        "    ]),",
        "    yield ActivityStub::make(MyActivity5::class),",
        "];",
        "```",
        "",
        "## Webhooks ##",
        "- Per abilitare i webhooks in Laravel Workflow, registrare le route nel file api.php:",
        "```php",
        "use Workflow\\Webhooks;",
        "Webhooks::routes();",
        "```",
        "- I workflow marcati con `#[Webhook]` sono esposti come endpoint pubblici.",
        "- Esempio di workflow marcato con webhook:",
        "```php",
        "use Workflow\\Webhook;",
        "use Workflow\\Workflow;",
        "",
        "#[Webhook]",
        "class OrderWorkflow extends Workflow {",
        "    public function execute($orderId) {",
        "        // codice di avvio",
        "    }",
        "}",
        "```",
        "- Per inviare un segnale via webhook:",
        "```php",
        "use Workflow\\SignalMethod;",
        "use Workflow\\Webhook;",
        "use Workflow\\Workflow;",
        "",
        "class OrderWorkflow extends Workflow {",
        "    protected bool $shipped = false;",
        "",
        "    #[SignalMethod]",
        "    #[Webhook]",
        "    public function markAsShipped() {",
        "        $this->shipped = true;",
        "    }",
        "}",
        "```",
        "",
        "Utilizza questi concetti per generare il codice Laravel richiesto.",
        "In particolare, se un workflow contiene activity di dispatch allora utilizza le istruzioni relative a webhooks per esporre gli endpoint pubblici e signals per ricevere notifiche.",
        "ESEMPIO DI WORKFLOW CON ACTIVITY IN PARALLELO:",
        "```php",
        "<?php",
        "namespace App\\Workflows;",
        "use Workflow\\Workflow;",
        "use Workflow\\ActivityStub;",
        "use App\\Workflows\\Activities\\TaskA;",
        "use App\\Workflows\\Activities\\TaskB;",
        "use App\\Workflows\\Activities\\TaskC;",
        "use App\\Workflows\\Activities\\TaskD;",
        "",
        "class GenericWorkflow extends Workflow {",
        "    public function execute() {",
        "        [$output1, $output2] = yield ActivityStub::all([",
        "            ActivityStub::make(TaskA::class),",
        "            ActivityStub::make(TaskB::class),",
        "        ]);",
        "        $output3 = yield ActivityStub::make(TaskC::class, $output1, $output2);",
        "        $output4 = yield ActivityStub::make(TaskD::class, $output3);",
        "        return $output4;",
        "    }",
        "}",
        "```",
        "",
        "FORMATO DI OUTPUT OBBLIGATORIO:",
        "Rispondi SOLO in JSON valido con la seguente struttura:",
        "```json",
        "{",
        "  'actors': [",
        "    {",
        "      'name': '<ActorName>',",
        "      'files': [",
        "        {'path': '<path_del_file>', 'content': '<codice_php_generato>'},",
        "        ...",
        "      ]",
        "    },",
        "    ...",
        "  ]",
        "}",
        "```",
        "",
        "Ogni attore quindi avrà un proprio insieme di file da salvare nel suo progetto Laravel.",
        "Non mescolare mai file di attori diversi nello stesso progetto o namespace.",
        "Non aggiungere testo esplicativo o descrizioni fuori dal JSON."
    ]

    return "\n".join(prompt)

def build_best_prompt(workflow_spec: str) -> str:
    prompt = [
        f"Genera codice per più progetti Laravel distinti (uno per ciascun attore) a partire dalla seguente specifica BPMN e basandoti sulle istruzioni fornite riguardo l'utilizzo della libreria Laravel Workflow.",
        "",
        "Ogni attore rappresenta un'entità autonoma, con un proprio progetto Laravel separato.",
        "Il codice di ciascun attore non deve essere inserito nello stesso progetto degli altri attori.",
        "",
        "Specifiche complete del BPMN (in formato JSON):",
        "```json",
        workflow_spec.strip(),
        "```",
        "",
        "# REQUISITI DI GENERAZIONE:",
        "- Identifica tutti gli attori presenti nella specifica (campo 'actors').",
        "- Per ogni attore genera il codice che popolerà il proprio progetto Laravel dedicato.",
        "- Ogni attore avrà i propri workflow, controller, servizi, activity e route, indipendenti da quelli degli altri.",
        "- Le comunicazioni tra attori, specificate nei messageFlow, avvengono tramite HTTP REST e devono essere rappresentate come chiamate verso endpoint pubblici degli altri attori.",
        "- Utilizza la libreria Laravel Workflow per implementare i workflow e le activity.",
        "- Se nella specifica del BPMN un attore è coinvolto in un CPPN, crea un workflow dedicato nella cartella app/Workflows che gestisce tutte le attività dell'attore all'interno del CPPN.",
        "- Se un attore compare come nel campo 'members' di un CPPN, crea un workflow dedicato nella cartella app/Workflows che gestisce le attività appartenenti a quell'attore all'interno del CPPN.",
        "- Non creare un singolo workflow che gestisce tutti i CPPN ma crea un workflow separato per ogni CPPN in cui è coinvolto l'attore.",
        "- Per ogni CPPS appartenente ad un attore, crea un workflow dedicato nella cartella app/Workflows che gestisce le attività dell'attore all'interno del CPPS.",
        "- Tratta un CPPS come un ChildWorkflowStub come descritto nelle istruzioni della libreria Laravel Workflow, da inserire all'interno del workflow principale (CPPN) dell'attore.",
        "- Se alcune attività presenti nel campo 'services' di un CPPN appartengono a un CPPS, crea un ChildWorkflowStub per il CPPS all'interno del workflow principale (CPPN) dell'attore.",
        "- Se un workflow CPPN contiene delle attività che fanno parte di un messageFlow allora bisogna marcare il workflow con l'attributo #[Webhook] per esporre un endpoint pubblico, come indicato nelle istruzioni dei Webhooks riportate sotto.",
        "- Se un'attività di un messageFlow appartiene al Production Leader e rappresenta la sorgente, allora quell'attività avrà il compito di far partire il workflow dell'attore che possiede l'attività identificata come destinazione nel messageFlow, "
        "  utilizzando le istruzioni dei Webhooks riportate sotto.",
        "- Se un'attività di un messageFlow appartiene al Production Leader e rappresenta la destinazione, allora quell'attività dovrà attendere un segnale esterno per proseguire l'esecuzione del workflow, utilizzando le istruzioni dei Signals riportate sotto.",
        "- Basati sulle istruzioni e gli esempi riportati in questo prompt per la generazione del codice Laravel.",
        "",
        "# STRUTTURA DI OGNI PROGETTO LARAVEL (PER OGNI ATTORE):",
        "- app/Workflows/: contiene le classi di orchestrazione dei workflow (es. ProductionLeaderWorkflow.php).",
        "- app/Activities/: contiene le activity usate dal workflow.",
        "- app/Services/: contiene le classi di servizio che implementano la logica di business.",
        "- app/Http/Controllers/: contiene i controller che espongono endpoint REST per avviare workflow o servizi atomici.",
        "- routes/api.php: definisce le route HTTP necessarie.",
        "",
        "# OGNI ATTORE DOVRÀ AVERE:",
        "1. Una o più classi Workflow per orchestrare le Activities in base al processo BPMN.",
        "2. Una classe per ogni Activity.",
        "3. Una classe Service per ogni servizio atomico.",
        "4. Un Controller per esporre endpoint pubblici.",
        "5. Le route associate, per ogni servizio atomico e CPPS registrate in routes/api.php.",
        "6. In caso di CPPS, il workflow principale dell'attore deve includere i ChildWorkflowStub per ogni CPPS in cui è coinvolto.",
        "7. Nel file api.php l'istruzione 'Webhooks::routes();' deve essere presente per abilitare i webhooks.",
        "",
        "# REGOLE PER I SERVIZI ATOMICI:",
        "- I servizi di tipo 'dispatch' devono effettuare chiamate HTTP POST verso endpoint di altri attori.",
        "- I servizi di tipo 'collect' devono ricevere chiamate HTTP e gestire i dati ricevuti nel rispettivo controller.",
        "",
        "# REGOLE DI DENOMINAZIONE DEI FILE:",
        "- Workflow: <ActorName>Workflow.php",
        "- Activity: <ServiceName>Activity.php",
        "- Service: <ServiceName>Service.php",
        "- Controller: <ServiceName>Controller.php",
        "",
        "# ISTRUZIONI PER L'USO DELLA LIBRERIA LARAVEL WORKFLOW:",
        "",
        "## Child Workflows ##",
        "- I child workflows permettono di suddividere processi complessi in sotto-processi gestibili.",
        "- Un child workflow è identico a un normale workflow, ma viene richiamato con `ChildWorkflowStub::make()` all’interno del workflow padre.",
        "- Esempio:",
        "```php",
        "use Workflow\\ChildWorkflowStub;",
        "use Workflow\\Workflow;",
        "",
        "class ParentWorkflow extends Workflow {",
        "    public function execute() {",
        "        $childResult = yield ChildWorkflowStub::make(ChildWorkflow::class);",
        "    }",
        "}",
        "```",
        "",
        "## Signals ##",
        "- I signals permettono di inviare eventi a un workflow dall'esterno.",
        "- Si definiscono con l’attributo `#[SignalMethod]` e `#[Webhook]` sul metodo del workflow.",
        "- Esempio:",
        "```php",
        "use Workflow\\SignalMethod;",
        "use Workflow\\Workflow;",
        "",
        "class MyWorkflow extends Workflow {",
        "    protected $ready = false;",
        "",
        "    #[SignalMethod]",
        "    #[Webhook]",
        "    public function setReady($ready) {",
        "        $this->ready = $ready;",
        "    }",
        "}",
        "```",
        "",
        "## Webhooks ##",
        "- Per abilitare i webhooks in Laravel Workflow, registrare le route nel file api.php:",
        "```php",
        "use Workflow\\Webhooks;",
        "Webhooks::routes();",
        "```",
        "- I workflow marcati con `#[Webhook]` sono esposti come endpoint pubblici.",
        "- Esempio di workflow marcato con webhook:",
        "```php",
        "use Workflow\\Webhook;",
        "use Workflow\\Workflow;",
        "",
        "#[Webhook]",
        "class OrderWorkflow extends Workflow {",
        "    public function execute($orderId) {",
        "        // codice di avvio",
        "    }",
        "}",
        "```",
        "- Esempio per l'attivazione di un workflow di un attore tramite webhook, mediata da Activity e Service:",
        "```php",
        "<?php",
        "",
        "namespace App\\Activities;",
        "",
        "use Workflow\\Activity;",
        "use App\\Services\\SendRequestService;",
        "",
        "class SendRequestActivity extends Activity",
        "{",
        "    public function execute()",
        "    {",
        "        $workflowId = $this->workflowId();",
        "        return app(SendRequestService::class)->sendRequest($workflowId);",
        "    }",
        "}",
        "```",
        "",
        "```php",
        "<?php",
        "",
        "use Illuminate\\Support\\Facades\\Http;",
        "",
        "class SendRequestService",
        "{",
        "    public function sendRequest($workflowId): array",
        "    {",
        "        $url = config('services.actor.url') . '/api/webhooks/start/actor-workflow';",
        "",
        "        $response = Http::post($url, [",
        "            'workflowId' => $workflowId,",
        "        ]);",
        "",
        "        return $response->json();",
        "    }",
        "}",
        "```",
        "- Esempio di invio di un segnale ad un workflow esterno:",
        "use Illuminate\\Support\\Facades\\Http;",
        "",
        "class SendRequestService",
        "{",
        "    public function send($workflowId)",
        "    {",
        "        $signalActorUrl = config('services.actor.url') . \"/api/webhooks/signal/actor-workflow/{$workflowId}/signal-method-name\";",
        "",
        "     $status = 1; // Esempio di stato da inviare",
        "        $response = Http::post($signalActorUrl, [",
        "            'status' => $status,",
        "        ]);",
        "",
        "        return $response->json();",
        "    }",
        "}",
        "",
        "- Esempio di workflow con gateway paralleli, gateway esclusivi e interazione tramite webhook e signal:",
        "```php",
        "<?php",
        "",
        "use Workflow\\Workflow;",
        "use Workflow\\ActivityStub;",
        "use Workflow\\ChildWorkflowStub;",
        "use Workflow\\SignalMethod;",
        "use Workflow\\Webhook;",
        "use Illuminate\\Support\\Facades\\Log;",
        "",
        "#[Webhook]",
        "class GenericOrchestrationWorkflow extends Workflow",
        "{",
        "    protected ?int $firstResponse = null;",
        "    protected ?int $secondResponse = null;",
        "",
        "    #[SignalMethod]",
        "    #[Webhook]",
        "    public function setFirstResponse(int $status)",
        "    {",
        "        Log::debug('Signal setFirstResponse received', ['status' => $status]);",
        "        $this->firstResponse = $status;",
        "    }",
        "",
        "    #[SignalMethod]",
        "    #[Webhook]",
        "    public function setSecondResponse(int $status)",
        "    {",
        "        Log::debug('Signal setSecondResponse received', ['status' => $status]);",
        "        $this->secondResponse = $status;",
        "    }",
        "",
        "    public function execute()",
        "    {",
        "        // Gateway parallelo: invio simultaneo di richieste a piu attori",
        "        yield ActivityStub::all([",
        "            ActivityStub::make(SendFirstRequestActivity::class),",
        "            ActivityStub::make(SendSecondRequestActivity::class),",
        "        ]);",
        "",
        "        $firstHandled = false;",
        "        $secondHandled = false;",
        "",
        "        // Attesa e gestione esclusiva delle risposte tramite signal",
        "        while (!($firstHandled && $secondHandled)) {",
        "            yield Workflow::await(fn () =>",
        "                ($this->firstResponse !== null && !$firstHandled) ||",
        "                ($this->secondResponse !== null && !$secondHandled)",
        "            );",
        "",
        "            if (!$firstHandled && $this->firstResponse !== null) {",
        "                yield ActivityStub::make(HandleFirstResponseActivity::class, $this->firstResponse);",
        "",
        "                if ($this->firstResponse === 1) {",
        "                    $firstHandled = true;",
        "                } else {",
        "                    $this->firstResponse = null;",
        "                    yield ActivityStub::make(SendFirstRequestActivity::class);",
        "                }",
        "            }",
        "",
        "            if (!$secondHandled && $this->secondResponse !== null) {",
        "                yield ActivityStub::make(HandleSecondResponseActivity::class, $this->secondResponse);",
        "",
        "                if ($this->secondResponse === 1) {",
        "                    $secondHandled = true;",
        "                } else {",
        "                    $this->secondResponse = null;",
        "                    yield ActivityStub::make(SendSecondRequestActivity::class);",
        "                }",
        "            }",
        "        }",
        "",
        "        // Avvio di un sottoprocesso tramite ChildWorkflow",
        "        $result = yield ChildWorkflowStub::make(SubProcessWorkflow::class);",
        "",
        "        // Attivita finale di notifica o consolidamento",
        "        yield ActivityStub::make(FinalizeProcessActivity::class, $result);",
        "",
        "        return $result;",
        "    }",
        "}",
        "```",
        "",
        "Utilizza questi esempi per generare il codice Laravel richiesto.",
        "## Concurrency ##",
        "- Le activity possono essere eseguite in serie o in parallelo usando `ActivityStub::make()` e `ActivityStub::all()`.",
        "- Esecuzione in serie:",
        "```php",
        "return [",
        "    yield ActivityStub::make(MyActivity1::class),",
        "    yield ActivityStub::make(MyActivity2::class),",
        "    yield ActivityStub::make(MyActivity3::class),",
        "];",
        "```",
        "- Esecuzione in parallelo:",
        "```php",
        "return yield ActivityStub::all([",
        "    ActivityStub::make(MyActivity1::class),",
        "    ActivityStub::make(MyActivity2::class),",
        "    ActivityStub::make(MyActivity3::class),",
        "]);",
        "```",
        "- È possibile combinare seriale e parallelo:",
        "```php",
        "return [",
        "    yield ActivityStub::make(MyActivity1::class),",
        "    yield ActivityStub::all([",
        "        ActivityStub::async(fn () => [",
        "            yield ActivityStub::make(MyActivity2::class),",
        "            yield ActivityStub::make(MyActivity3::class),",
        "        ]),",
        "        ActivityStub::make(MyActivity4::class),",
        "    ]),",
        "    yield ActivityStub::make(MyActivity5::class),",
        "];",
        "```",
        "ESEMPIO DI WORKFLOW CON ACTIVITY IN PARALLELO:",
        "```php",
        "<?php",
        "namespace App\\Workflows;",
        "use Workflow\\Workflow;",
        "use Workflow\\ActivityStub;",
        "use App\\Workflows\\Activities\\TaskA;",
        "use App\\Workflows\\Activities\\TaskB;",
        "use App\\Workflows\\Activities\\TaskC;",
        "use App\\Workflows\\Activities\\TaskD;",
        "",
        "class GenericWorkflow extends Workflow {",
        "    public function execute() {",
        "        [$output1, $output2] = yield ActivityStub::all([",
        "            ActivityStub::make(TaskA::class),",
        "            ActivityStub::make(TaskB::class),",
        "        ]);",
        "        $output3 = yield ActivityStub::make(TaskC::class, $output1, $output2);",
        "        $output4 = yield ActivityStub::make(TaskD::class, $output3);",
        "        return $output4;",
        "    }",
        "}",
        "```",
        "",
        "FORMATO DI OUTPUT OBBLIGATORIO:",
        "Rispondi SOLO in JSON valido con la seguente struttura:",
        "```json",
        "{",
        "  'actors': [",
        "    {",
        "      'name': '<ActorName>',",
        "      'files': [",
        "        {'path': '<path_del_file>', 'content': '<codice_php_generato>'},",
        "        ...",
        "      ]",
        "    },",
        "    ...",
        "  ]",
        "}",
        "```",
        "",
        "Ogni attore quindi avrà un proprio insieme di file da salvare nel suo progetto Laravel.",
        "Non mescolare mai file di attori diversi nello stesso progetto o namespace.",
        "Non aggiungere testo esplicativo o descrizioni fuori dal JSON."
    ]

    return "\n".join(prompt)


def build_prompt_zero_shot(workflow_spec: str) -> str:
    prompt = [
        "Genera codice per progetti Laravel distinti basandoti sulla specifica BPMN fornita e sulla libreria laravel-workflow.",
        "",
        "Specifica BPMN (JSON):",
        "```json", workflow_spec.strip(), "```",
        "",
        "ISTRUZIONI:",
        "- Crea un progetto Laravel separato per ogni attore nella specifica",
        "- Ogni attore ha workflow, controller, servizi, activity e route indipendenti",
        "- Comunicazioni tra attori tramite HTTP REST",
        "- Struttura: app/Workflows/, app/Activities/, app/Services/, app/Http/Controllers/, routes/api.php",
        "- Nomenclatura: <ActorName>Workflow.php, <ServiceName>Activity.php, <ServiceName>Service.php, <ServiceName>Controller.php",
        "- Servizi 'dispatch': chiamate HTTP POST ad altri attori",
        "- Servizi 'collect': ricevono chiamate HTTP",
        "",
        "FORMATO DI OUTPUT OBBLIGATORIO:",
        "Rispondi SOLO in JSON valido con la seguente struttura:",
        "```json",
        "{",
        "  'actors': [",
        "    {",
        "      'name': '<ActorName>',",
        "      'files': [",
        "        {'path': '<path_del_file>', 'content': '<codice_php_generato>'},",
        "        ...",
        "      ]",
        "    },",
        "    ...",
        "  ]",
        "}",
        "```"
    ]
    return "\n".join(prompt)


def build_prompt_few_shot(workflow_spec: str) -> str:
    prompt = [
        "Genera codice per più progetti Laravel distinti (uno per ciascun attore) a partire dalla seguente specifica BPMN, utilizzando la libreria Laravel Workflow.",
        "",
        "Ogni attore è un progetto Laravel indipendente con il proprio namespace e le proprie route.",
        "",
        "Specifica BPMN (JSON):",
        "```json",
        workflow_spec.strip(),
        "```",
        "",
        "REQUISITI DI GENERAZIONE:",
        "- Identifica tutti gli attori presenti nella specifica (campo 'actors').",
        "- Per ogni attore genera il codice che popolerà il proprio progetto Laravel dedicato.",
        "- Ogni attore avrà i propri workflow, controller, servizi, activity e route, indipendenti da quelli degli altri.",
        "- Le comunicazioni tra attori (servizi di tipo 'dispatch' o 'collect') avvengono tramite HTTP REST e devono essere rappresentate come chiamate verso endpoint pubblici degli altri attori.",
        "- Utilizza la libreria Laravel Workflow per implementare i workflow e le activity.",
        "- Se nella specifica del BPMN un attore è coinvolto in un CPPN, crea un workflow dedicato nella cartella app/Workflows che gestisce tutte le attività dell'attore all'interno del CPPN.",
        "- Per ogni CPPS appartenente ad un attore, crea un workflow dedicato nella cartella app/Workflows che gestisce le attività dell'attore all'interno del CPPS.",
        "- Se un attore compare in 2 o più CPPN, crea un workflow separato per ogni CPPN in cui è coinvolto.",
        "- Tratta un CPPS come un ChildWorkflowStub come descritto nelle istruzioni della libreria Laravel Workflow, da inserire all'interno del workflow principale (CPPN) dell'attore.",
        "",
        "STRUTTURA DI OGNI PROGETTO LARAVEL (PER OGNI ATTORE):",
        "- app/Workflows/: contiene le classi di orchestrazione dei workflow (es. ProductionLeaderWorkflow.php).",
        "- app/Activities/: contiene le activity usate dal workflow.",
        "- app/Services/: contiene le classi di servizio che implementano la logica di business.",
        "- app/Http/Controllers/: contiene i controller che espongono endpoint REST per avviare workflow o servizi atomici.",
        "- routes/api.php: definisce le route HTTP necessarie.",
        "",
        "OGNI ATTORE DOVRÀ AVERE:",
        "1. Una o più classi Workflow per orchestrare le Activity in base al processo BPMN.",
        "2. Una classe per ogni Activity.",
        "3. Una classe Service per ogni servizio atomico.",
        "4. Un Controller per esporre endpoint pubblici.",
        "5. Le route associate, per ogni servizio atomico e CPPS registrate in routes/api.php.",
        "6. In caso di CPPS, il workflow principale dell'attore deve includere i ChildWorkflowStub per ogni CPPS in cui è coinvolto.",
        "7. Nel file api.php l'istruzione 'Webhooks::routes();' deve essere presente per abilitare i webhooks.",
        "",
        "REGOLE PER I SERVIZI ATOMICI:",
        "- I servizi di tipo 'dispatch' devono effettuare chiamate HTTP POST verso endpoint di altri attori.",
        "- I servizi di tipo 'collect' devono ricevere chiamate HTTP e gestire i dati ricevuti nel rispettivo controller.",
        "",
        "ESEMPI DI CODICE LIBRERIA LARAVEL WORKFLOW:",
        "",
        "### Workflow con Activity in parallelo ###",
        "```php",
        "<?php",
        "namespace App\\Workflows;",
        "use Workflow\\Workflow;",
        "use Workflow\\ActivityStub;",
        "",
        "class ExampleWorkflow extends Workflow {",
        "    public function execute() {",
        "        [$a, $b] = yield ActivityStub::all([",
        "            ActivityStub::make(TaskA::class),",
        "            ActivityStub::make(TaskB::class),",
        "        ]);",
        "        return yield ActivityStub::make(TaskC::class, $a, $b);",
        "    }",
        "}",
        "```",
        "",
        "### Esempio di Child Workflow ###",
        "```php",
        "use Workflow\\ChildWorkflowStub;",
        "",
        "class ParentWorkflow extends Workflow {",
        "    public function execute() {",
        "        yield ChildWorkflowStub::make(SubProcessWorkflow::class);",
        "    }",
        "}",
        "```",
        "",
        "### Esempio di Signal ###",
        "```php",
        "use Workflow\\SignalMethod;",
        "use Workflow\\Workflow;",
        "",
        "class ApprovalWorkflow extends Workflow {",
        "    protected bool $approved = false;",
        "",
        "    #[SignalMethod]",
        "    public function approve() { $this->approved = true; }",
        "",
        "    public function execute() {",
        "        yield Workflow::await(fn() => $this->approved);",
        "        yield ActivityStub::make(FinalizeActivity::class);",
        "    }",
        "}",
        "```",
        "",
        "FORMATO DI OUTPUT OBBLIGATORIO:",
        "Rispondi SOLO in JSON valido con la seguente struttura:",
        "```json",
        "{",
        "  'actors': [",
        "    {",
        "      'name': '<ActorName>',",
        "      'files': [",
        "        {'path': '<path_del_file>', 'content': '<codice_php_generato>'},",
        "        ...",
        "      ]",
        "    },",
        "    ...",
        "  ]",
        "}",
        "```",
        "",
        "Non includere spiegazioni o testo esterno: restituisci solo il JSON finale."
    ]

    return "\n".join(prompt)


def build_prompt_cot_zero_shot(workflow_spec: str) -> str:
    prompt = [
        "Genera codice per progetti Laravel distinti basati sulla specifica BPMN fornita.",
        "Segui questo processo di ragionamento passo-passo:",
        "",
        "Specifica BPMN (JSON):",
        "```json", workflow_spec.strip(), "```",
        "",
        "RAGIONAMENTO RICHIESTO (includi nel processo mentale, non nell'output):",
        "Passo 1: Analizza la specifica BPMN ed elenca tutti gli attori presenti",
        "Passo 2: Per ogni attore, identifica i servizi che deve implementare",
        "Passo 3: Determina quali servizi sono 'dispatch' (inviano dati) e quali 'collect' (ricevono dati)",
        "Passo 4: Identifica le dipendenze tra servizi e l'ordine di esecuzione nel workflow",
        "Passo 5: Determina quali activity possono essere eseguite in parallelo (usa ActivityStub::all([]))",
        "Passo 6: Per ogni attore, progetta la struttura completa dei file necessari:",
        "   - Workflow principale con orchestrazione",
        "   - Activity per ogni servizio del workflow",
        "   - Service per logica business",
        "   - Controller per endpoint REST",
        "   - Route in api.php",
        "Passo 7: Genera il codice PHP completo per ogni file di ogni attore",
        "Passo 8: Verifica che ogni attore sia completamente autonomo e indipendente",
        "Passo 9: Controlla che le comunicazioni inter-attore usino HTTP REST correttamente",
        "",
         "REQUISITI DI GENERAZIONE:",
        "- Identifica tutti gli attori presenti nella specifica (campo 'actors').",
        "- Per ogni attore genera il codice che popolerà il proprio progetto Laravel dedicato.",
        "- Ogni attore avrà i propri workflow, controller, servizi, activity e route, indipendenti da quelli degli altri.",
        "- Le comunicazioni tra attori (servizi di tipo 'dispatch' o 'collect') avvengono tramite HTTP REST e devono essere rappresentate come chiamate verso endpoint pubblici degli altri attori.",
        "- Utilizza la libreria Laravel Workflow per implementare i workflow e le activity.",
        "- Se nella specifica del BPMN un attore è coinvolto in un CPPN, crea un workflow dedicato nella cartella app/Workflows che gestisce tutte le attività dell'attore all'interno del CPPN.",
        "- Per ogni CPPS appartenente ad un attore, crea un workflow dedicato nella cartella app/Workflows che gestisce le attività dell'attore all'interno del CPPS.",
        "- Se un attore compare in 2 o più CPPN, crea un workflow separato per ogni CPPN in cui è coinvolto.",
        "- Tratta un CPPS come un ChildWorkflowStub come descritto nelle istruzioni della libreria Laravel Workflow, da inserire all'interno del workflow principale (CPPN) dell'attore.",
        "",
        "STRUTTURA DI OGNI PROGETTO LARAVEL (PER OGNI ATTORE):",
        "- app/Workflows/: contiene le classi di orchestrazione dei workflow (es. ProductionLeaderWorkflow.php).",
        "- app/Activities/: contiene le activity usate dal workflow.",
        "- app/Services/: contiene le classi di servizio che implementano la logica di business.",
        "- app/Http/Controllers/: contiene i controller che espongono endpoint REST per avviare workflow o servizi atomici.",
        "- routes/api.php: definisce le route HTTP necessarie.",
        "",
        "OGNI ATTORE DOVRÀ AVERE:",
        "1. Una o più classi Workflow per orchestrare le Activity in base al processo BPMN.",
        "2. Una classe per ogni Activity.",
        "3. Una classe Service per ogni servizio atomico.",
        "4. Un Controller per esporre endpoint pubblici.",
        "5. Le route associate, per ogni servizio atomico e CPPS registrate in routes/api.php.",
        "6. In caso di CPPS, il workflow principale dell'attore deve includere i ChildWorkflowStub per ogni CPPS in cui è coinvolto.",
        "7. Nel file api.php l'istruzione 'Webhooks::routes();' deve essere presente per abilitare i webhooks.",
        "",
        "REGOLE PER I SERVIZI ATOMICI:",
        "- I servizi di tipo 'dispatch' devono effettuare chiamate HTTP POST verso endpoint di altri attori.",
        "- I servizi di tipo 'collect' devono ricevere chiamate HTTP e gestire i dati ricevuti nel rispettivo controller.",
        "",
        "FORMATO DI OUTPUT OBBLIGATORIO:",
        "Rispondi SOLO in JSON valido con la seguente struttura:",
        "```json",
        "{",
        "  'actors': [",
        "    {",
        "      'name': '<ActorName>',",
        "      'files': [",
        "        {'path': '<path_del_file>', 'content': '<codice_php_generato>'},",
        "        ...",
        "      ]",
        "    },",
        "    ...",
        "  ]",
        "}",
        "```",
        "",
        "Non includere il ragionamento nell'output JSON, solo il codice generato."
    ]
    return "\n".join(prompt)


def build_prompt_persona(workflow_spec: str) -> str:
    """
    PERSONA PATTERN: il modello assume il ruolo di un esperto senior Laravel architect.
    """
    prompt = [
        "Sei un Senior Laravel Architect con 10+ anni di esperienza in microservizi e orchestrazione di workflow.",
        "Hai costruito decine di sistemi BPMN-based usando Laravel e Temporal/Workflow.",
        "Sei riconosciuto per codice pulito, architetture scalabili e best practices.",
        "",
        "IL TUO COMPITO:",
        "Progetta e genera codice Laravel per un sistema multi-attore basato sulla seguente specifica BPMN.",
        "",
        "Specifica BPMN (JSON):",
        "```json", workflow_spec.strip(), "```",
        "",
        "APPLICA LA TUA EXPERTISE:",
        "- Architettura microservizi: ogni attore è un servizio Laravel indipendente",
        "- Separazione delle responsabilità: Workflow (orchestrazione), Activity (step atomici), Service (business logic), Controller (API layer)",
        "- Pattern di comunicazione: REST HTTP per inter-service communication",
        "- Gestione concorrenza: ActivityStub::all([]) per task paralleli",
        "- Naming conventions professionali e consistenti",
        "- Codice production-ready con error handling e type hints",
        "",
        "STRUTTURA TECNICA PER OGNI ATTORE:",
        "- app/Workflows/<ActorName>Workflow.php: orchestrazione principale",
        "- app/Workflows/Activities/<ServiceName>Activity.php: activity atomiche",
        "- app/Services/<ServiceName>Service.php: business logic",
        "- app/Http/Controllers/<ServiceName>Controller.php: REST endpoints",
        "- routes/api.php: route definitions",
        "",
        "SPECIFICHE IMPLEMENTATIVE:",
        "- Servizi 'dispatch': usa Http::post() per chiamare endpoint esterni",
        "- Servizi 'collect': esponi endpoint POST per ricevere dati",
        "- Workflow: yield ActivityStub per orchestrazione asincrona",
        "- Validazione input nei controller con FormRequest",
        "- Dependency injection per servizi e repository",
        "",
        "FORMATO DI OUTPUT OBBLIGATORIO:",
        "Rispondi SOLO in JSON valido con la seguente struttura:",
        "```json",
        "{",
        "  'actors': [",
        "    {",
        "      'name': '<ActorName>',",
        "      'files': [",
        "        {'path': '<path_del_file>', 'content': '<codice_php_generato>'},",
        "        ...",
        "      ]",
        "    },",
        "    ...",
        "  ]",
        "}",
        "```",
        "",
        "Come Senior Architect, assicurati che ogni file sia completo, funzionale e segua le best practices Laravel."
    ]
    return "\n".join(prompt)




def build_prompt_self_refine(workflow_spec: str) -> str:
    """
    SELF-REFINE: il modello genera, critica e migliora iterativamente.
    """
    prompt = [
        "Genera codice Laravel per progetti multi-attore basati su specifica BPMN.",
        "Usa un processo iterativo di generazione e refinement.",
        "",
        "Specifica BPMN (JSON):",
        "```json", workflow_spec.strip(), "```",
        "",
        "PROCESSO DI SELF-REFINEMENT:",
        "",
        "FASE 1 - GENERAZIONE INIZIALE:",
        "Genera una prima versione del codice per tutti gli attori seguendo queste regole:",
        "- Un progetto Laravel separato per ogni attore",
        "- Struttura: Workflows, Activities, Services, Controllers, Routes",
        "- Nomenclatura: <ActorName>Workflow.php, <ServiceName>Activity.php, etc.",
        "",
        "FASE 2 - AUTO-CRITICA (verifica mentale):",
        "Esamina criticamente il codice generato chiedendoti:",
        "✓ Ogni attore è veramente indipendente? No dipendenze cross-project?",
        "✓ I servizi 'dispatch' effettuano correttamente chiamate HTTP?",
        "✓ I servizi 'collect' hanno endpoint REST per ricevere dati?",
        "✓ Il workflow orchestra correttamente le activity con yield?",
        "✓ Le activity parallele usano ActivityStub::all([])?",
        "✓ I namespace sono corretti e consistenti?",
        "✓ Le route sono registrate correttamente in api.php?",
        "✓ Il codice segue PSR e Laravel best practices?",
        "✓ Ci sono error handling e validazioni?",
        "",
        "FASE 3 - REFINEMENT:",
        "Migliora il codice basandoti sulla critica:",
        "- Correggi eventuali errori di architettura",
        "- Aggiungi gestione errori dove manca",
        "- Ottimizza pattern di comunicazione tra attori",
        "- Assicura coerenza nei naming e structure",
        "- Completa qualsiasi codice placeholder",
        "",
        "FASE 4 - VALIDAZIONE FINALE:",
        "Verifica che:",
        "- Output sia JSON valido nel formato richiesto",
        "- Ogni file contenga codice PHP completo e funzionale",
        "- Non ci siano dipendenze circolari o accoppiamenti stretti",
        "- Ogni attore possa essere deployato indipendentemente",
        "",
        "REQUISITI TECNICI:",
        "- Struttura directory: app/Workflows/, app/Workflows/Activities/, app/Services/, app/Http/Controllers/, routes/api.php",
        "- Dispatch: use Illuminate\\Support\\Facades\\Http; Http::post()",
        "- Collect: controller pubblico con Request $request",
        "- Workflow: use Workflow\\ActivityStub; yield ActivityStub::make()",
        "",
        "FORMATO DI OUTPUT OBBLIGATORIO:",
        "Rispondi SOLO in JSON valido con la seguente struttura:",
        "```json",
        "{",
        "  'actors': [",
        "    {",
        "      'name': '<ActorName>',",
        "      'files': [",
        "        {'path': '<path_del_file>', 'content': '<codice_php_generato>'},",
        "        ...",
        "      ]",
        "    },",
        "    ...",
        "  ]",
        "}",
        "```",
        "",
        "Fornisci solo la versione finale refined del codice, non le iterazioni intermedie."
    ]
    return "\n".join(prompt)